# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Szemely',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('szemely_nev', models.CharField(max_length=50)),
                ('tel_szam', models.CharField(max_length=12)),
                ('reg_dat', models.DateTimeField(verbose_name='date registered')),
            ],
        ),
    ]
